# Generated by Django 2.2a1 on 2019-03-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_name', models.CharField(max_length=30)),
                ('to_user_name', models.CharField(max_length=50)),
                ('transfer_credit', models.CharField(max_length=20)),
            ],
        ),
    ]
