# Generated by Django 2.2a1 on 2019-03-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Delhi', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(default='xxxxxxxx45', max_length=20),
            preserve_default=False,
        ),
    ]
