# Generated by Django 2.2a1 on 2019-03-07 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20190307_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
